### ISSUE TITLE
Thief Detection : Alerting Police Stations using Notifications and Image of an Intruder

### ISSUE THREAD

**Issue by prathimacode-hub** [neha07kumari/Thief_Detection#11]
### Description

Welcome to 'Thief -Detection', good to see you here.

With this issue, the readers will get to know on how to alert police stations using notifications and image of an intruder

It's an interlinked issue with earlier issue of Thief Detection and House Owner Alerts. Discuss with the collaborator assigned to issue number - 6 and 7 and work accordingly

To get assigned to this issue, add your participant id mentioned in this [spreadsheet](https://docs.google.com/spreadsheets/d/1SX9FubA-n1ag_0n4WmzMXd6rq5lrkFmaAWl8fhHvTWM/edit#gid=0) and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot is must to approve 

This issue is only for 'SWOC' contributors

### Domain

Data Science

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/neha07kumari/Thief_Detection/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/neha07kumari/Thief_Detection/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by hassanrahim26** [comment]
Hey @prathimacode-hub, I would like to work on this issue. Can you please tell me ways to get started?
I'm an SWOC contributor.
Participant Id:- 399

**Comment by prathimacode-hub** [comment]
Yes, sure. Its an interlinked issue so kindly interact with issue number : 6 and 7 collaborator to initiate the progress. It's a continuation of issue 6. After a person is detected to be thief or not, we should continue with alerting police stations using Notifications and sending the image of an intruder along with it. So your focus should be on this scope, after a person is detected as thief. @HassanRahim26

**Comment by prathimacode-hub** [comment]
So do you like to take up this issue? Provide the details mentioned to get it assigned. @HassanRahim26

**Comment by krishna-NIT** [comment]
@prathimacode-hub I can do this
We can send alerts to police stations via Telegram, Discord, or Slack
We can send image too there via a bot
Please assign me this issue so that I can make it happen soon!

**Comment by prathimacode-hub** [comment]
Lets see if @HassanRahim26 responds within 2 days if not you can take it up. Once u finish earlier issue, let me know @krishna-NIT

**Comment by hassanrahim26** [comment]
I want to work on this issue. Can you please tell me how to get started with it?
@prathimacode-hub

**Comment by krishna-NIT** [comment]
> Lets see if @HassanRahim26 responds within 2 days if not you can take it up. Once u finish earlier issue, let me know @krishna-NIT

Ma'am should I move ahead or wait?

**Comment by prathimacode-hub** [comment]
You can use some notifier to send alerts to police stations along with image of intruder using api and where you want to send out an alert. @HassanRahim26 

@krishna-NIT, @HassanRahim26 has already responded with interest to do as is expecting guidance. Lets give him a chance. You can choose another issue. There are many more to come.

**Comment by krishna-NIT** [comment]
> You can use some notifier to send alerts to police stations along with image of intruder using api and where you want to send out an alert. @HassanRahim26
> 
> @krishna-NIT, @HassanRahim26 has already responded with interest to do as is expecting guidance. Lets give him a chance. You can choose another issue. There are many more to come.

Sure Ma'am 👍🏻 
All the best @HassanRahim26 You can and you will!

**Comment by hassanrahim26** [comment]
> You can use some notifier to send alerts to police stations along with image of intruder using api and where you want to send out an alert. @HassanRahim26
> 
> @krishna-NIT, @HassanRahim26 has already responded with interest to do as is expecting guidance. Lets give him a chance. You can choose another issue. There are many more to come.

I'll start working on this issue. Thanks, for the guidance @prathimacode-hub 😄

**Comment by prathimacode-hub** [comment]
You're welcome @HassanRahim26
