### ISSUE TITLE
Thief Detection : Alerting Protection Centers using Notifications and Images of an Intruder

### ISSUE THREAD

**Issue by prathimacode-hub** [neha07kumari/Thief_Detection#12]
### Description

Welcome to 'Thief -Detection', good to see you here.

With this issue, the readers will get to know on how to alert protection centers using notifications and image of an intruder

It's an interlinked issue with earlier issue of Thief Detection, House Owner Alerts, Police Station Alerts. Discuss with the collaborator assigned to issue number - 6, 7 and 11 to work accordingly

To get assigned to this issue, add your participant id mentioned in this [spreadsheet](https://docs.google.com/spreadsheets/d/1SX9FubA-n1ag_0n4WmzMXd6rq5lrkFmaAWl8fhHvTWM/edit#gid=0) and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot is must to approve 

This issue is only for 'SWOC' contributors

### Domain

Data Science

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/neha07kumari/Thief_Detection/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/neha07kumari/Thief_Detection/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by krishna-NIT** [comment]
@prathimacode-hub I can do this by using Notifly
We can send alerts to Protection Centers via Telegram, Discord, or Slack
We can send images too there via a bot
Please assign me this issue so that I can make it happen soon!

**Comment by prathimacode-hub** [comment]
Issue assigned to @krishna-NIT. You can proceed. Can you add your participant id too?

**Comment by krishna-NIT** [comment]
> Issue assigned to @krishna-NIT. You can proceed. Can you add your participant id too?

Sure Ma'am
My Participant ID is 930
