### ISSUE TITLE
Create About Us Section in Home Page

### ISSUE THREAD

**Issue by amitrakshar01** [neha07kumari/Thief_Detection#4]
### Description

Welcome to 'Thief -Detection', good to see you here.

With this issue, the readers will get to know on how to add about us section and provide the detailing linked to Home Page

To get assigned to this issue, add your participant id mentioned in this [spreadsheet](https://docs.google.com/spreadsheets/d/1SX9FubA-n1ag_0n4WmzMXd6rq5lrkFmaAWl8fhHvTWM/edit#gid=0) and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot and Video of the Outlook of the changes is must to approve 

This issue is only for 'SWOC' contributors

### Domain

Web Development

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/neha07kumari/Thief_Detection/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/neha07kumari/Thief_Detection/blob/main/CODE_OF_CONDUCT.md) of this project.

All the best. Enjoy your open source journey ahead. 😎

**Comment by kkg2001** [comment]
I want to work on this issue #4

**Comment by amitrakshar01** [comment]
> I want to work on this issue #4

Assigned. Follow all contributing guidelines

**Comment by amitrakshar01** [comment]
@kkg2001 any updates on the work?

**Comment by kkg2001** [comment]
I have created the about us section in html but I didnt knew what content to add in 'about us' so I have taken reference from the GITHUB page of this project. Due to my college exams I was not able to focus much onto this. Exams will be over in 2 days time. I will be sharing snippets of my work, let me know what changes I have to make regarding font size and the background and what content I should add in the 'about us section' and in general also.
![S1](https://user-images.githubusercontent.com/82452511/146670177-3675bae6-220a-442b-bb9e-87071f2a91b5.png)
![SS2](https://user-images.githubusercontent.com/82452511/146670182-cfced67b-a975-4729-aaa4-2bd3477a748c.png)
![S3](https://user-images.githubusercontent.com/82452511/146670192-ebaac42d-e374-4c7d-80f1-85b0caa1d912.png)
![S4](https://user-images.githubusercontent.com/82452511/146670194-d991690b-b59a-4aa7-8edb-148576ff29aa.png)

Thanks.

**Comment by amitrakshar01** [comment]
> I have created the about us section in html but I didnt knew what content to add in 'about us' so I have taken reference from the GITHUB page of this project. Due to my college exams I was not able to focus much onto this. Exams will be over in 2 days time. I will be sharing snippets of my work, let me know what changes I have to make regarding font size and the background and what content I should add in the 'about us section' and in general also. ![S1](https://user-images.githubusercontent.com/82452511/146670177-3675bae6-220a-442b-bb9e-87071f2a91b5.png) ![SS2](https://user-images.githubusercontent.com/82452511/146670182-cfced67b-a975-4729-aaa4-2bd3477a748c.png) ![S3](https://user-images.githubusercontent.com/82452511/146670192-ebaac42d-e374-4c7d-80f1-85b0caa1d912.png) ![S4](https://user-images.githubusercontent.com/82452511/146670194-d991690b-b59a-4aa7-8edb-148576ff29aa.png)
> 
> Thanks.

Font looks great, just change the header with something more interesting

**Comment by kkg2001** [comment]
Ok I will change it. Also do let me know the content part in the 'about us' section that I should include, whether I have to give a description of the owners and mentors of this project and stuff like contact details or only details about the project and guidelines and details about tech stack which I was already doing. 
Thanks

**Comment by prathimacode-hub** [comment]
Yes, make font size similar for all and highlight subheadings. And this is issue is only for "About Section". Other sections will come in form of issue. In about, it only should have description of the project. For time being, you can refer to the issues created, mentioned in repo description and add up the detailing accordingly. Don't give other things. @kkg2001

**Comment by kkg2001** [comment]
Is it fine if I am using bootstrap for this?

**Comment by prathimacode-hub** [comment]
lets get with basic first and then enhance it. @kkg2001

**Comment by kkg2001** [comment]
![2021-12-31](https://user-images.githubusercontent.com/82452511/147832035-084c4558-ae25-4c08-87aa-41586f2d346a.png)
![2021-12-31 (1)](https://user-images.githubusercontent.com/82452511/147832053-e0184eaa-344b-44fb-9ce1-0172d0013b3a.png)
![2021-12-31 (2)](https://user-images.githubusercontent.com/82452511/147832067-0e36aabf-a559-4c7b-a01d-4433e90c3144.png)
![2021-12-31 (3)](https://user-images.githubusercontent.com/82452511/147832077-e32fd23b-01b9-4c4e-9590-113266138300.png)
![2021-12-31 (4)](https://user-images.githubusercontent.com/82452511/147832089-9e453afc-3a9a-4ed1-ac59-46ebbb019a02.png)
![2021-12-31 (5)](https://user-images.githubusercontent.com/82452511/147832099-a19ead70-7a96-405f-9703-740c2ea003db.png)
![2021-12-31 (6)](https://user-images.githubusercontent.com/82452511/147832105-777cb810-4834-4776-9f2e-01c6eb32c73f.png)

**Comment by kkg2001** [comment]
I have designed it. Only thing is I am not able to get the bulleted points in straight line. Let me know the changes before I publish here

**Comment by prathimacode-hub** [comment]
I think, you positioned your alignment to center so depends on line length it shows unparallel @kkg2001

**Comment by kkg2001** [comment]
Yeah thanks, I have fixed that now. Regarding 'contact us' link I have not
added redirecting link and in 'website' link it will redirect to the thief
detection website and 'linkedin' and 'twitter' will redirect to the
respective websites.
Let me know if there are any changes overall to be made and then I will
merge a pull request. Is it fine?
Thanks

**Comment by prathimacode-hub** [comment]
Yup, all good to make a PR. Slight change for contact us link, use a random mail id for time being. Proceed ahead. @kkg2001

**Comment by kkg2001** [comment]
Yes I made the required change in contact us link and I have merged the PR.
Thanks.
