### ISSUE TITLE
Thief-Detection : Alerts House Owner using Notification

### ISSUE THREAD

**Issue by prathimacode-hub** [neha07kumari/Thief_Detection#7]
### Description

Welcome to 'Thief -Detection', good to see you here.

With this issue, the readers will get to know on how to alert house owner using notification if a person is detected as a thief.

It's an interlinked issue with previous issue of Thief Detection. Discuss with the collaborator assigned to issue number-6 and work accordingly

To get assigned to this issue, add your participant id mentioned in this [spreadsheet](https://docs.google.com/spreadsheets/d/1SX9FubA-n1ag_0n4WmzMXd6rq5lrkFmaAWl8fhHvTWM/edit#gid=0) and the approach you would follow.

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title" should be the same. Include issue number in PR template along with it.

- You should add up in respective folder according to the demands of the issue.

- Inclusion of Screenshot is must to approve 

This issue is only for 'SWOC' contributors

### Domain

Data Science

### Code of Conduct

- [X] I  will follow [Contributing Guidelines](https://github.com/neha07kumari/Thief_Detection/blob/main/CONTRIBUTING.md) & [Code of conduct](https://github.com/neha07kumari/Thief_Detection/blob/main/CODE_OF_CONDUCT.md) of this project.

**Comment by kkg2001** [comment]
I want to work on this issue #7

**Comment by prathimacode-hub** [comment]
You can do work on this after your previous issue number #6  is done. @kkg2001

**Comment by krishna-NIT** [comment]
@prathimacode-hub I am ready with code for notification in this, Please assign me so that I can raise PR in this issue Participant ID : 930

**Comment by krishna-NIT** [comment]
> You can do work on this after your previous issue number #6 is done. @kkg2001

Done, I am ready to move this ahead so, please assign me ID : 930

**Comment by prathimacode-hub** [comment]
Ok issue assigned to @krishna-NIT. Proceed

**Comment by krishna-NIT** [comment]
PR done 👍🏻 
@prathimacode-hub
